stages:
- name: compile-scratch
  steps:
  - publishImageConfig:
      dockerfilePath: ./scratch/Dockerfile
      buildContext: .
      tag: phpcode
      registry: registry-vpc.cn-beijing.aliyuncs.com
timeout: 60
