stages:
- name: compile-scratch
  steps:
  - publishImageConfig:
      dockerfilePath: ./nginx/Dockerfile
      buildContext: .
      tag: php-nginx
      registry: registry-vpc.cn-beijing.aliyuncs.com
timeout: 60
